/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.boot.SpringApplication;

@SpringBootApplication
public class App {
//change
    public static void main(String[] args) {
        ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
        SpringApplication.run(App.class, args);
    }
}
