/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.classes.Man;
import org.example.classes.Person;
import org.example.classes.PersonInvocationHandler;

import java.lang.reflect.Proxy;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Man zaid = new Man("Zaid", 10 , "Delhi", "India");
        ClassLoader zaidClassLoader = zaid.getClass().getClassLoader();

        Class[] interfaces = zaid.getClass().getInterfaces();
        Person proxyZaid = (Person) Proxy.newProxyInstance(zaidClassLoader, interfaces, new PersonInvocationHandler(zaid));

        proxyZaid.introduce(zaid.getName());
    }
}
